# Wazuh Docker Compose - Single Node Deployment
# Based on Wazuh 4.7.3 official configuration

version: '3.8'

services:
  # Wazuh Indexer (Elasticsearch-based)
  wazuh-indexer:
    image: wazuh/wazuh-indexer:${WAZUH_STACK_VERSION}
    container_name: wazuh-indexer
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer
      - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.indexer-key.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.key
      - ./config/wazuh_indexer_ssl_certs/wazuh.indexer.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.pem
      - ./config/wazuh_indexer_ssl_certs/admin.pem:/usr/share/wazuh-indexer/certs/admin.pem
      - ./config/wazuh_indexer_ssl_certs/admin-key.pem:/usr/share/wazuh-indexer/certs/admin-key.pem
      - ./config/wazuh-indexer/wazuh.indexer.yml:/usr/share/wazuh-indexer/opensearch.yml
      - ./config/wazuh-indexer/internal_users.yml:/usr/share/wazuh-indexer/opensearch-security/internal_users.yml
    networks:
      - wazuh-network
    healthcheck:
      test: ["CMD-SHELL", "curl -XGET https://localhost:9200 -u admin:admin -k"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Wazuh Manager
  wazuh-manager:
    image: wazuh/wazuh-manager:${WAZUH_STACK_VERSION}
    container_name: wazuh-manager
    restart: always
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://wazuh-indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=${INDEXER_PASSWORD}
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
    volumes:
      - wazuh-manager-data:/var/ossec/data
      - wazuh-manager-logs:/var/ossec/logs
      - wazuh-manager-etc:/var/ossec/etc
      - wazuh-manager-integrations:/var/ossec/integrations
      - wazuh-manager-active-response:/var/ossec/active-response/bin
      - wazuh-manager-agentless:/var/ossec/agentless
      - wazuh-manager-wodles:/var/ossec/wodles
      - ./config/wazuh_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.manager.pem:/etc/ssl/filebeat.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.manager-key.pem:/etc/ssl/filebeat.key
      - ./config/wazuh-manager/wazuh.manager.conf:/wazuh-config-mount/etc/ossec.conf
      - ./config/wazuh-manager/local_rules.xml:/var/ossec/etc/rules/local_rules.xml
      - ./config/wazuh-manager/local_decoders.xml:/var/ossec/etc/decoders/local_decoders.xml
    networks:
      - wazuh-network
    depends_on:
      wazuh-indexer:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "/var/ossec/bin/wazuh-control status"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Wazuh Dashboard (Kibana-based)
  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:${WAZUH_STACK_VERSION}
    container_name: wazuh-dashboard
    restart: always
    ports:
      - "443:5601"
    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=${INDEXER_PASSWORD}
      - WAZUH_API_URL=https://wazuh-manager
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
      - DASHBOARD_USERNAME=${DASHBOARD_USERNAME}
      - DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}
    volumes:
      - ./config/wazuh_indexer_ssl_certs/wazuh.dashboard.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.dashboard-key.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
      - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem
      - ./config/wazuh-dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
      - ./config/wazuh-dashboard/wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
    networks:
      - wazuh-network
    depends_on:
      wazuh-manager:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -XGET https://localhost:5601/app/wazuh -k"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  wazuh-indexer-data:
    driver: local
  wazuh-manager-data:
    driver: local
  wazuh-manager-logs:
    driver: local
  wazuh-manager-etc:
    driver: local
  wazuh-manager-integrations:
    driver: local
  wazuh-manager-active-response:
    driver: local
  wazuh-manager-agentless:
    driver: local
  wazuh-manager-wodles:
    driver: local

networks:
  wazuh-network:
    driver: bridge
    name: wazuh-network